### ISSUE TITLE
Three quick improvement suggestions

### ISSUE THREAD

**Issue by Eyremba** [DeBukkIt/SimpleFileStorage#5]
1. Send some kind of warning message when a password is longer than 16 chars, because if it is longer than 16 characters, only the first 16 characters will be used for the encryption.

2. If the password in DB.get("ID", "PASSWORD"); is wrong, it throws an exception:

javax.crypto.BadPaddingException: Given final block not properly padded
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:989)
	at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:845)
	at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
	at javax.crypto.Cipher.doFinal(Cipher.java:2165)
	at com.blogspot.debukkitsblog.Crypt.Crypter.decrypt(Crypter.java:54)
	at com.blogspot.debukkitsblog.Crypt.Crypter.decrypt(Crypter.java:33)
	at com.blogspot.debukkitsblog.Util.FileStorage.get(FileStorage.java:117)
	at dbtest.main(Main.java:37)
Exception in thread "main" java.lang.NullPointerException
	at dbtest.main(Main.java:37)

instead, it should either print a message with "Wrong password" or something like this, or it should print out the "garbage" of the decryption result, but not an error. :D 

Edit:

3: Please add the ability to specify the password key too in getAll() and printAll() :D

**Comment by DeBukkIt** [comment]
Would you like to fork the project, implement these improvements and start a pull request?

**Comment by Eyremba** [comment]
> Would you like to fork the project, implement these improvements and start a pull request?

I'm still learning Java, so I'm not sure if my Java skills are good enough to implement all of this correctly. :(

**Comment by DeBukkIt** [comment]
Deine drei Vorschläge sind als Änderungssätze f7df0c15a4c0b66b90c2b9893dad2fbf9813142e, 0b4cce5f5b4c440789afb9d7fe4a1a79521234b6 und eacd334da1b221b570ec9f98783c1903f9f2c436 mit kleineren Änderungen und weiteren Ergänzungen übernommen worden.

**Comment by Eyremba** [comment]
Vielen Dank. :)
